apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vote-deployment.yaml
- vote-service.yaml

namespace: instavote

images: 
  - name: schoolofdevops/vote
  - newTag: v3

replicas:
  - name: vote
    count: 3
